FROM ubuntu:22.04

ARG ARG_VCS_REF

LABEL \
    org.opencontainers.image.authors="Ebabil Software" \
    org.opencontainers.image.description="Ebabil Ubuntu 22.04 Base Image" \
    org.opencontainers.image.documentation="https://github.com/Murat-Koes-54/ebx-ubuntu" \
    org.opencontainers.image.source="https://github.com/Murat-Koes-54/ebx-ubuntu" \
    org.opencontainers.image.title="ebx-ubuntu" \
    org.opencontainers.image.url="https://github.com/Murat-Koes-54/ebx-ubuntu" \
    org.opencontainers.image.vendor="Ebabil Software"

LABEL \
    org.label-scheme.vcs-url="https://github.com/Murat-Koes-54/ebx-ubuntu" \
    org.label-scheme.vcs-ref="${ARG_VCS_REF}"